//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestService.CustomerSvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerSvc.ICustomerServices")]
    public interface ICustomerServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerServices/GetFavorites", ReplyAction="http://tempuri.org/ICustomerServices/GetFavoritesResponse")]
        string GetFavorites(out string favoriteMovie, out string favoriteLanguage, string firstName, string lastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerServices/UpdateFavoritesByName", ReplyAction="http://tempuri.org/ICustomerServices/UpdateFavoritesByNameResponse")]
        string UpdateFavoritesByName(string firstName, string lastName, string favoriteMovie, string favoriteLanguage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerServices/GetCustomerList", ReplyAction="http://tempuri.org/ICustomerServices/GetCustomerListResponse")]
        string GetCustomerList(out System.Data.DataSet customers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerServices/AddACustomer", ReplyAction="http://tempuri.org/ICustomerServices/AddACustomerResponse")]
        string AddACustomer(string firstName, string lastName, string favoriteMovie, string favoriteLanguage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerServices/SubmitToQueue", ReplyAction="http://tempuri.org/ICustomerServices/SubmitToQueueResponse")]
        string SubmitToQueue(string firstName, string lastName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerServicesChannel : TestService.CustomerSvc.ICustomerServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServicesClient : System.ServiceModel.ClientBase<TestService.CustomerSvc.ICustomerServices>, TestService.CustomerSvc.ICustomerServices {
        
        public CustomerServicesClient() {
        }
        
        public CustomerServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetFavorites(out string favoriteMovie, out string favoriteLanguage, string firstName, string lastName) {
            return base.Channel.GetFavorites(out favoriteMovie, out favoriteLanguage, firstName, lastName);
        }
        
        public string UpdateFavoritesByName(string firstName, string lastName, string favoriteMovie, string favoriteLanguage) {
            return base.Channel.UpdateFavoritesByName(firstName, lastName, favoriteMovie, favoriteLanguage);
        }
        
        public string GetCustomerList(out System.Data.DataSet customers) {
            return base.Channel.GetCustomerList(out customers);
        }
        
        public string AddACustomer(string firstName, string lastName, string favoriteMovie, string favoriteLanguage) {
            return base.Channel.AddACustomer(firstName, lastName, favoriteMovie, favoriteLanguage);
        }
        
        public string SubmitToQueue(string firstName, string lastName) {
            return base.Channel.SubmitToQueue(firstName, lastName);
        }
    }
}
